wip: fix j2 fdpic libgcc c++ build
In file included from ../../../../src_gcc/libstdc++-v3/libsupc++/eh_call.cc:32:
/home/patrick/src/toolchain/musl-cross-make/build/local/sh2eb-linux-muslfdpic/src_gcc/libstdc++-v3/../libgcc/unwind-pe.h:
In function 'const unsigned char*
read_encoded_value_with_base(unsigned char, _Unwind_Ptr, const unsigned char*, _Unwind_Ptr*)':
/home/patrick/src/toolchain/musl-cross-make/build/local/sh2eb-linux-muslfdpic/src_gcc/libstdc++-v3/../libgcc/unwind-pe.h:270:25:
error: '_Unwind_gnu_Find_got' was not declared in this scope
  270 |               result += _Unwind_gnu_Find_got ((_Unwind_Ptr) u);
      |                         ^~~~~~~~~~~~~~~~~~~~

Patch posted by Thalheim in #musl-offtopic. Thanks!

Unfortunately this doesn't work yet because of a cowpatch issue - the
build gets the unpatched file:

realpath /tmp/makepkg/sh2eb-linux-muslfdpic/src/musl-cross-make/build/local/sh2eb-linux-muslfdpic/src_gcc/libstdc++-v3/../libgcc/unwind-pe.h
/tmp/makepkg/sh2eb-linux-muslfdpic/src/musl-cross-make/gcc-11.1.0.orig/libgcc/unwind-pe.h